export const CHANGE_SEARCH_FIELDS = 'CHANGE_SEARCH_FIELDS';
export const REQUEST_ROBOTS_FAILURE = 'REQUEST_ROBOTS_FAILURE';
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';